export const ActionTypes = {
    FETCH_ARTICLES: "FETCH_ARTICLES",
    UPDATE_PROP: "UPDATE_PROP",
    RESET: "RESET",
    CREATE_DESTINATIONS: "CREATE_DESTINATIONS",
    CREATE_TRIP: "CREATE_TRIP",
    CREATE_PHOTO: "CREATE_PHOTO",
    FETCH_TRIP: "FETCH_TRIP",
    UPDATE_TRIP: "UPDATE_TRIP",
    CREATE_STICKER: "CREATE_STICKER",
    SET_CREATE_STICKER: "SET_CREATE_STICKER",
    DELETE_PHOTO: "DELETE_PHOTO",
    DELETE_STICKER: "DELETE_STICKER",
};